[package]
name = "minor-relay-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
minor-relay = { path = ".." }

[[bin]]
name = "wire_decode"
path = "fuzz_targets/wire_decode.rs"
test = false
doc = false
bench = false

[[bin]]
name = "persisted_decode"
path = "fuzz_targets/persisted_decode.rs"
test = false
doc = false
bench = false

[[bin]]
name = "selector"
path = "fuzz_targets/selector.rs"
test = false
doc = false
bench = false

# Prevent this from interfering with workspaces
[workspace]
members = ["."]
